kind: pipeline
name: x64

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: gcc:8
  commands:
  - make 
  - make quiettest 
  - make amalgamate

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: gcc:8
  commands:
  - make 
  - make quiettest 
  - make amalgamate



