var searchData=
[
  ['data_0',['data',['../structsimdjson_1_1padded__string.html#aa833ecdbe40c220c5baf7a29c472c972',1,'simdjson::padded_string::data() noexcept'],['../structsimdjson_1_1padded__string.html#aadd3bb268cbba43012c5d17a8c1ab7ef',1,'simdjson::padded_string::data() const noexcept']]],
  ['de_20serialization_20of_20a_20member_1',['Custom (de)serialization of a member',['../md_doc_2basics.html#autotoc_md26',1,'']]],
  ['de_20serialization_20with_20annotations_2',['Customizing (de)serialization with annotations',['../md_doc_2basics.html#autotoc_md19',1,'']]],
  ['decimal_5fpoint_3',['decimal_point',['../structsimdjson__fast__float_1_1parse__options__t.html#a6afc71b8003f36543ef9bec66b4b3eaa',1,'simdjson_fast_float::parse_options_t']]],
  ['default_20ndjson_20json_20lines_4',['Whitespace-delimited (default, NDJSON / JSON Lines)',['../md_doc_2iterate__many.html#autotoc_md159',1,'']]],
  ['default_20values_5',['Default values',['../md_doc_2basics.html#autotoc_md22',1,'']]],
  ['default_5fmax_5fdepth_6',['DEFAULT_MAX_DEPTH',['../namespacesimdjson.html#a6df2598eb1d4e1ea669c41831cc7325d',1,'simdjson']]],
  ['delimited_20default_20ndjson_20json_20lines_7',['Whitespace-delimited (default, NDJSON / JSON Lines)',['../md_doc_2iterate__many.html#autotoc_md159',1,'']]],
  ['delimited_20documents_8',['Comma-delimited documents',['../md_doc_2iterate__many.html#autotoc_md160',1,'']]],
  ['delimited_20json_20ndjson_20and_20json_20lines_9',['Newline-Delimited JSON (ndjson) and JSON lines',['../md_doc_2basics.html#autotoc_md53',1,'']]],
  ['demand_10',['demand',['../md_doc_2dom.html#autotoc_md110',1,'DOM vs On-Demand'],['../md_doc_2basics.html#autotoc_md33',1,'Using &lt;tt&gt;for_each_at_path_with_wildcard&lt;/tt&gt; for JSONPath Queries (On-Demand)']]],
  ['demand_20approach_11',['demand approach',['../md_doc_2ondemand__design.html#autotoc_md174',1,'Applicability of the On-Demand Approach'],['../md_doc_2ondemand__design.html#autotoc_md172',1,'Benefits of the On-Demand Approach'],['../md_doc_2ondemand__design.html#autotoc_md173',1,'Limitations of the On-Demand Approach']]],
  ['dependency_12',['Using simdjson as a CMake dependency',['../md_doc_2basics.html#autotoc_md3',1,'']]],
  ['deprecated_13',['Legacy &lt;tt&gt;allow_comma_separated&lt;/tt&gt; parameter (deprecated)',['../md_doc_2iterate__many.html#autotoc_md153',1,'']]],
  ['deprecated_20list_14',['Deprecated List',['../deprecated.html',1,'']]],
  ['depth_15',['depth',['../md_doc_2dom.html#autotoc_md125',1,'Limiting the maximum depth'],['../md_doc_2basics.html#autotoc_md62',1,'Limiting the maximum depth']]],
  ['depth_5ferror_16',['DEPTH_ERROR',['../namespacesimdjson.html#a7b735a3a50ba79e3f7f14df5f77d8da9a0c6b4af181d3d5f40a09182522c88681',1,'simdjson']]],
  ['depth_5ft_17',['depth_t',['../namespacesimdjson_1_1_s_i_m_d_j_s_o_n___i_m_p_l_e_m_e_n_t_a_t_i_o_n_1_1ondemand.html#af941be7ff0cfaeb30d15d2fb52e76dd1',1,'simdjson::SIMDJSON_IMPLEMENTATION::ondemand']]],
  ['describe_20tt_18',['Inspecting the matching algorithm with &lt;tt&gt;describe()&lt;/tt&gt;',['../md_doc_2basics.html#autotoc_md44',1,'']]],
  ['description_19',['description',['../classsimdjson_1_1implementation.html#ab170b9fed9cab0daaff878472f339c40',1,'simdjson::implementation']]],
  ['deserialization_20c_2026_20',['Order-independent reflective deserialization (C++26)',['../md_doc_2basics.html#autotoc_md28',1,'']]],
  ['design_21',['design',['../md_doc_2parse__many.html#autotoc_md181',1,'Design'],['../md_doc_2iterate__many.html#autotoc_md142',1,'Design']]],
  ['design_20features_22',['Design Features',['../md_doc_2ondemand__design.html#autotoc_md169',1,'']]],
  ['detected_20implementation_23',['Inspecting the Detected Implementation',['../md_doc_2implementation-selection.html#autotoc_md134',1,'']]],
  ['detection_24',['Runtime CPU Detection',['../md_doc_2implementation-selection.html#autotoc_md133',1,'']]],
  ['development_20checks_25',['Avoiding pitfalls: enable development checks',['../md_doc_2basics.html#autotoc_md11',1,'']]],
  ['direct_20access_20to_20the_20raw_20json_20string_26',['General direct access to the raw JSON string',['../md_doc_2basics.html#autotoc_md58',1,'']]],
  ['direct_20extraction_27',['Example 3: Direct Extraction',['../md_doc_2compile__time__accessors.html#autotoc_md104',1,'']]],
  ['direct_20field_20extraction_28',['Direct Field Extraction',['../md_doc_2compile__time__accessors.html#autotoc_md100',1,'']]],
  ['directly_20from_20a_20memory_20mapped_20file_29',['directly from a memory mapped file',['../md_doc_2parse__many.html#autotoc_md187',1,'Streaming directly from a memory-mapped file'],['../md_doc_2iterate__many.html#autotoc_md147',1,'Streaming directly from a memory-mapped file']]],
  ['directly_20into_20an_20existing_20string_20instance_30',['Storing directly into an existing string instance',['../md_doc_2basics.html#autotoc_md60',1,'']]],
  ['disabling_20exceptions_31',['Disabling exceptions',['../md_doc_2basics.html#autotoc_md48',1,'']]],
  ['disk_32',['Loading from disk',['../md_doc_2compile__time.html#autotoc_md82',1,'']]],
  ['doc_33',['doc',['../classsimdjson_1_1_s_i_m_d_j_s_o_n___i_m_p_l_e_m_e_n_t_a_t_i_o_n_1_1dom__parser__implementation.html#a4089d6265ec845fd85acd2db0973b858',1,'simdjson::SIMDJSON_IMPLEMENTATION::dom_parser_implementation']]],
  ['document_34',['document',['../md_doc_2basics.html#autotoc_md50',1,'Current location in document'],['../classsimdjson_1_1_s_i_m_d_j_s_o_n___i_m_p_l_e_m_e_n_t_a_t_i_o_n_1_1ondemand_1_1document.html',1,'simdjson::SIMDJSON_IMPLEMENTATION::ondemand::document'],['../classsimdjson_1_1dom_1_1document.html',1,'simdjson::dom::document'],['../classsimdjson_1_1_s_i_m_d_j_s_o_n___i_m_p_l_e_m_e_n_t_a_t_i_o_n_1_1ondemand_1_1document.html#a54cd729a715a09bc9e706b7640233427',1,'simdjson::SIMDJSON_IMPLEMENTATION::ondemand::document::document()'],['../classsimdjson_1_1dom_1_1document.html#af34f108b46f82428bfe4ea33869358f0',1,'simdjson::dom::document::document(document &amp;&amp;other) noexcept=default'],['../classsimdjson_1_1dom_1_1document.html#a6947c9d79453071ca73d06e398bcdd2a',1,'simdjson::dom::document::document() noexcept=default']]],
  ['document_20and_20json_20scope_35',['Parser, document and JSON scope',['../md_doc_2basics.html#autotoc_md8',1,'']]],
  ['document_20lifetime_36',['document lifetime',['../classsimdjson_1_1dom_1_1parser.html#autotoc_md217',1,'IMPORTANT: Document Lifetime'],['../classsimdjson_1_1dom_1_1parser.html#autotoc_md221',1,'IMPORTANT: Document Lifetime'],['../classsimdjson_1_1_s_i_m_d_j_s_o_n___i_m_p_l_e_m_e_n_t_a_t_i_o_n_1_1ondemand_1_1parser.html#autotoc_md235',1,'IMPORTANT: Document Lifetime'],['../classsimdjson_1_1dom_1_1parser.html#autotoc_md216',1,'IMPORTANT: Document Lifetime'],['../classsimdjson_1_1dom_1_1parser.html#autotoc_md213',1,'IMPORTANT: Document Lifetime'],['../classsimdjson_1_1_s_i_m_d_j_s_o_n___i_m_p_l_e_m_e_n_t_a_t_i_o_n_1_1ondemand_1_1parser.html#autotoc_md239',1,'IMPORTANT: Document Lifetime']]],
  ['document_20object_20model_20dom_20front_20end_37',['The Document-Object-Model (DOM) front-end',['../md_doc_2dom.html',1,'']]],
  ['document_20stream_38',['document stream',['../md_doc_2parse__many.html#autotoc_md192',1,'JSON Array As A Document Stream'],['../md_doc_2iterate__many.html#autotoc_md155',1,'JSON Array As A Document Stream']]],
  ['document_5fdepth_39',['DOCUMENT_DEPTH',['../classsimdjson_1_1_s_i_m_d_j_s_o_n___i_m_p_l_e_m_e_n_t_a_t_i_o_n_1_1ondemand_1_1document.html#a18847ef30e5800f1c628a344c23ec968',1,'simdjson::SIMDJSON_IMPLEMENTATION::ondemand::document']]],
  ['document_5freference_40',['document_reference',['../classsimdjson_1_1_s_i_m_d_j_s_o_n___i_m_p_l_e_m_e_n_t_a_t_i_o_n_1_1ondemand_1_1document__reference.html',1,'simdjson::SIMDJSON_IMPLEMENTATION::ondemand']]],
  ['document_5fstream_41',['document_stream',['../classsimdjson_1_1dom_1_1document__stream.html',1,'simdjson::dom::document_stream'],['../classsimdjson_1_1_s_i_m_d_j_s_o_n___i_m_p_l_e_m_e_n_t_a_t_i_o_n_1_1ondemand_1_1document__stream.html',1,'simdjson::SIMDJSON_IMPLEMENTATION::ondemand::document_stream'],['../classsimdjson_1_1dom_1_1document__stream.html#ae6ee894790448145e11a456f12253364',1,'simdjson::dom::document_stream::document_stream() noexcept'],['../classsimdjson_1_1dom_1_1document__stream.html#a9d6bb44a7d8f818c401d65fb80f6a523',1,'simdjson::dom::document_stream::document_stream(document_stream &amp;&amp;other) noexcept=default'],['../classsimdjson_1_1_s_i_m_d_j_s_o_n___i_m_p_l_e_m_e_n_t_a_t_i_o_n_1_1ondemand_1_1document__stream.html#af12dc14d4d16b9f4f4602c738678cb0c',1,'simdjson::SIMDJSON_IMPLEMENTATION::ondemand::document_stream::document_stream() noexcept'],['../classsimdjson_1_1_s_i_m_d_j_s_o_n___i_m_p_l_e_m_e_n_t_a_t_i_o_n_1_1ondemand_1_1document__stream.html#a0ac2a6ad0393eb4330b440c8c09290f2',1,'simdjson::SIMDJSON_IMPLEMENTATION::ondemand::document_stream::document_stream(document_stream &amp;&amp;other) noexcept=default']]],
  ['documents_42',['documents',['../md_doc_2ondemand__design.html',1,'A Better Way to Parse Documents?'],['../md_doc_2iterate__many.html#autotoc_md161',1,'A single JSON array as a stream of documents'],['../md_doc_2iterate__many.html#autotoc_md160',1,'Comma-delimited documents'],['../md_doc_2iterate__many.html#autotoc_md151',1,'Comma-separated documents'],['../md_doc_2parse__many.html#autotoc_md190',1,'Comma-Separated Documents'],['../md_doc_2basics.html#autotoc_md5',1,'The basics: loading and parsing JSON documents']]],
  ['documents_20are_20iterators_43',['Documents are iterators',['../md_doc_2basics.html#autotoc_md7',1,'']]],
  ['documents_20using_20the_20dom_20front_20end_44',['The Basics: Loading and Parsing JSON Documents using the DOM front-end',['../md_doc_2dom.html#autotoc_md111',1,'']]],
  ['dom_20api_45',['Best Use of the DOM API',['../md_doc_2dom.html#autotoc_md128',1,'']]],
  ['dom_20front_20end_46',['dom front end',['../md_doc_2dom.html#autotoc_md111',1,'The Basics: Loading and Parsing JSON Documents using the DOM front-end'],['../md_doc_2dom.html',1,'The Document-Object-Model (DOM) front-end']]],
  ['dom_20parsers_47',['DOM Parsers',['../md_doc_2ondemand__design.html#autotoc_md163',1,'']]],
  ['dom_20vs_20on_20demand_48',['DOM vs On-Demand',['../md_doc_2dom.html#autotoc_md110',1,'']]],
  ['dom_5fparser_5fimplementation_49',['dom_parser_implementation',['../classsimdjson_1_1_s_i_m_d_j_s_o_n___i_m_p_l_e_m_e_n_t_a_t_i_o_n_1_1dom__parser__implementation.html',1,'simdjson::SIMDJSON_IMPLEMENTATION']]],
  ['double_50',['DOUBLE',['../namespacesimdjson_1_1dom.html#a6e1dee3a823ecfee91086d3478bbab3aafd3e4ece78a7d422280d5ed379482229',1,'simdjson::dom']]],
  ['double_20values_51',['Integer and Double values',['../md_doc_2tape.html#autotoc_md207',1,'']]],
  ['downclocking_52',['Power Usage and Downclocking',['../md_doc_2performance.html#autotoc_md200',1,'']]],
  ['dynamic_20number_20types_53',['Dynamic Number Types',['../md_doc_2basics.html#autotoc_md55',1,'']]]
];
