#ifndef SIMDJSON_DEVELOPMENT_CHECKS
#define SIMDJSON_DEVELOPMENT_CHECKS 0
#endif

#if SIMDJSON_DEVELOPMENT_CHECKS != SIMDJSON_EXPECT_DEVELOPMENT_CHECKS
#error SIMDJSON_DEVELOPMENT_CHECKS has an unexpected value
#endif

int main() { return 0; }
