[package]
name = "serde-benchmark"
version = "0.1.0"

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
libc = "0.2"
serde_json = "1.0"

[profile.release]
opt-level = 3
debug = false
lto = true
