#ifndef SIMDJSON_CONDITIONAL_INCLUDE
#include "simdjson/westmere/base.h"
#endif // SIMDJSON_CONDITIONAL_INCLUDE

#if !SIMDJSON_CAN_ALWAYS_RUN_WESTMERE
SIMDJSON_UNTARGET_REGION
#endif

#undef SIMDJSON_IMPLEMENTATION
