#ifndef SIMDJSON_WESTMERE_TARGET_H
#define SIMDJSON_WESTMERE_TARGET_H

#include "simdjson/common_defs.h"

#if SIMDJSON_CAN_ALWAYS_RUN_WESTMERE
#define SIMDJSON_TARGET_WESTMERE
#define SIMDJSON_UNTARGET_WESTMERE
#else
#define SIMDJSON_TARGET_WESTMERE SIMDJSON_TARGET_REGION("sse4.2,pclmul,popcnt")
#define SIMDJSON_UNTARGET_WESTMERE SIMDJSON_UNTARGET_REGION
#endif

#endif // SIMDJSON_WESTMERE_TARGET_H