// /include/simdjson/simdjson_version.h automatically generated by release.py, do not change by hand 
#ifndef SIMDJSON_INCLUDE_SIMDJSON_VERSION 
#define SIMDJSON_INCLUDE_SIMDJSON_VERSION 
#define SIMDJSON_VERSION 0.1.1 
enum { 
    SIMDJSON_VERSION_MAJOR = 0,  
    SIMDJSON_VERSION_MINOR = 1,  
    SIMDJSON_VERSION_REVISION = 1  
}; 
#endif // SIMDJSON_INCLUDE_SIMDJSON_VERSION 
