#!/bin/sh
#
# Regenerates include/simdjson/internal/fast_float.h from an upstream fast_float
# release. The vendored copy is never edited by hand.
#
#   tools/vendor_fast_float.sh 8.2.10
#   tools/vendor_fast_float.sh --from-file path/to/fast_float.h [version]
#
# Two transformations are applied. First, everything fast_float declares is
# renamed so that a program can link simdjson and its own copy of fast_float in
# the same translation unit: the namespace becomes simdjson_fast_float, and the
# FASTFLOAT_/fastfloat_ macros (include guards among them) pick up a SIMDJSON_
# prefix. Second, the accented letters in the attribution comments are folded to
# ASCII, because simdjson keeps its whole tree ASCII-only (the just_ascii test).

set -eu

FROM_FILE=""
VERSION="8.2.10"
if [ "${1:-}" = "--from-file" ]; then
  FROM_FILE="${2:?--from-file requires a path to an amalgamated fast_float.h}"
  VERSION="${3:-8.2.10}"
elif [ -n "${1:-}" ]; then
  VERSION="$1"
fi

URL="https://github.com/fastfloat/fast_float/releases/download/v${VERSION}/fast_float.h"
OUT="$(dirname "$0")/../include/simdjson/internal/fast_float.h"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

if [ -n "$FROM_FILE" ]; then
  cp "$FROM_FILE" "$TMP"
else
  curl -sSfL -o "$TMP" "$URL"
fi

VERSION="$VERSION" OUT="$OUT" TMP="$TMP" python3 - <<'PYTHON'
import os, re, unicodedata

version = os.environ["VERSION"]
source = open(os.environ["TMP"], encoding="utf-8").read()

# Private namespace, so this copy cannot collide with the program's own.
source = re.sub(r"\bfast_float\b", "simdjson_fast_float", source)
source = re.sub(r"\bFASTFLOAT_", "SIMDJSON_FASTFLOAT_", source)
source = re.sub(r"\bfastfloat_", "simdjson_fastfloat_", source)

# Fold accents so the tree stays ASCII-only. This only ever touches comments.
folded = unicodedata.normalize("NFKD", source).encode("ascii", "ignore").decode("ascii")
assert folded.isascii(), "fast_float still has non-ASCII characters after folding"

banner = f"""// Vendored from fast_float v{version}, generated by tools/vendor_fast_float.sh.
// Do not edit by hand; re-run the script to update.
//
//   https://github.com/fastfloat/fast_float
//   Licensed under Apache-2.0 OR MIT OR BSL-1.0, at your option.
//
// simdjson uses this for two things that its own number parser cannot do:
//   * the slow path for numbers with more than 19 significant digits, where
//     fast_float's bigint comparison is several times quicker than the
//     Wuffs-derived decimal shifting it replaced (see src/from_chars.cpp), and
//   * correctly rounded parsing inside a constant expression, which the runtime
//     path cannot offer because it relies on memcpy and __uint128_t (see
//     compile_time_json-inl.h).
//
// Two edits are applied by the script. Every fast_float name is rewritten so
// that this copy cannot collide with a copy of fast_float that the surrounding
// program includes for itself: namespace fast_float -> simdjson_fast_float,
// FASTFLOAT_* -> SIMDJSON_FASTFLOAT_*, fastfloat_* -> simdjson_fastfloat_*. And
// the accented letters in the attribution comments below are folded to ASCII,
// to keep the tree ASCII-only; no disrespect to the people named is intended.
"""

open(os.environ["OUT"], "w", encoding="ascii").write(banner + folded)
PYTHON

echo "wrote $OUT ($(wc -c < "$OUT") bytes) from fast_float v${VERSION}"
