set(sources
        include/simdjson/arm64/begin.h
        include/simdjson/arm64/bitmanipulation.h
        include/simdjson/arm64/bitmask.h
        include/simdjson/arm64/end.h
        include/simdjson/arm64/implementation.h
        include/simdjson/arm64/intrinsics.h
        include/simdjson/arm64/numberparsing.h
        include/simdjson/arm64/simd.h
        include/simdjson/arm64/stringparsing.h
        include/simdjson/arm64.h
        include/simdjson/builtin.h
        include/simdjson/common_defs.h
        include/simdjson/compiler_check.h
        include/simdjson/dom/array-inl.h
        include/simdjson/dom/array.h
        include/simdjson/dom/document-inl.h
        include/simdjson/dom/document.h
        include/simdjson/dom/document_stream-inl.h
        include/simdjson/dom/document_stream.h
        include/simdjson/dom/element-inl.h
        include/simdjson/dom/element.h
        include/simdjson/dom/jsonparser.h
        include/simdjson/dom/object-inl.h
        include/simdjson/dom/object.h
        include/simdjson/dom/parsedjson.h
        include/simdjson/dom/parsedjson_iterator-inl.h
        include/simdjson/dom/parsedjson_iterator.h
        include/simdjson/dom/parser-inl.h
        include/simdjson/dom/parser.h
        include/simdjson/dom/serialization-inl.h
        include/simdjson/dom/serialization.h
        include/simdjson/error-inl.h
        include/simdjson/error.h
        include/simdjson/fallback/begin.h
        include/simdjson/fallback/bitmanipulation.h
        include/simdjson/fallback/end.h
        include/simdjson/fallback/implementation.h
        include/simdjson/fallback/numberparsing.h
        include/simdjson/fallback/stringparsing.h
        include/simdjson/fallback.h
        include/simdjson/generic/atomparsing.h
        include/simdjson/generic/dom_parser_implementation.h
        include/simdjson/generic/implementation_simdjson_result_base-inl.h
        include/simdjson/generic/implementation_simdjson_result_base.h
        include/simdjson/generic/jsoncharutils.h
        include/simdjson/generic/numberparsing.h
        include/simdjson/generic/ondemand/array-inl.h
        include/simdjson/generic/ondemand/array.h
        include/simdjson/generic/ondemand/array_iterator-inl.h
        include/simdjson/generic/ondemand/array_iterator.h
        include/simdjson/generic/ondemand/document-inl.h
        include/simdjson/generic/ondemand/document.h
        include/simdjson/generic/ondemand/field-inl.h
        include/simdjson/generic/ondemand/field.h
        include/simdjson/generic/ondemand/json_iterator-inl.h
        include/simdjson/generic/ondemand/json_iterator.h
        include/simdjson/generic/ondemand/logger-inl.h
        include/simdjson/generic/ondemand/logger.h
        include/simdjson/generic/ondemand/object-inl.h
        include/simdjson/generic/ondemand/object.h
        include/simdjson/generic/ondemand/object_iterator-inl.h
        include/simdjson/generic/ondemand/object_iterator.h
        include/simdjson/generic/ondemand/parser-inl.h
        include/simdjson/generic/ondemand/parser.h
        include/simdjson/generic/ondemand/raw_json_string-inl.h
        include/simdjson/generic/ondemand/raw_json_string.h
        include/simdjson/generic/ondemand/token_iterator-inl.h
        include/simdjson/generic/ondemand/token_iterator.h
        include/simdjson/generic/ondemand/value-inl.h
        include/simdjson/generic/ondemand/value.h
        include/simdjson/generic/ondemand-inl.h
        include/simdjson/generic/ondemand.h
        include/simdjson/generic/stringparsing.h
        include/simdjson/haswell/begin.h
        include/simdjson/haswell/bitmanipulation.h
        include/simdjson/haswell/bitmask.h
        include/simdjson/haswell/end.h
        include/simdjson/haswell/implementation.h
        include/simdjson/haswell/intrinsics.h
        include/simdjson/haswell/numberparsing.h
        include/simdjson/haswell/simd.h
        include/simdjson/haswell/stringparsing.h
        include/simdjson/haswell.h
        include/simdjson/implementation.h
        include/simdjson/internal/dom_parser_implementation.h
        include/simdjson/internal/isadetection.h
        include/simdjson/internal/jsoncharutils_tables.h
        include/simdjson/internal/jsonformatutils.h
        include/simdjson/internal/numberparsing_tables.h
        include/simdjson/internal/simdprune_tables.h
        include/simdjson/internal/tape_ref-inl.h
        include/simdjson/internal/tape_ref.h
        include/simdjson/internal/tape_type.h
        include/simdjson/jsonioutil.h
        include/simdjson/minify.h
        include/simdjson/padded_string-inl.h
        include/simdjson/padded_string.h
        include/simdjson/portability.h
        include/simdjson/simdjson.h
        include/simdjson/simdjson_version.h
        include/simdjson/westmere/begin.h
        include/simdjson/westmere/bitmanipulation.h
        include/simdjson/westmere/bitmask.h
        include/simdjson/westmere/end.h
        include/simdjson/westmere/implementation.h
        include/simdjson/westmere/intrinsics.h
        include/simdjson/westmere/numberparsing.h
        include/simdjson/westmere/simd.h
        include/simdjson/westmere/stringparsing.h
        include/simdjson/westmere.h
        include/simdjson.h
        src/arm64/dom_parser_implementation.cpp
        src/arm64/implementation.cpp
        src/fallback/dom_parser_implementation.cpp
        src/fallback/implementation.cpp
        src/from_chars.cpp
        src/generic/stage1/buf_block_reader.h
        src/generic/stage1/find_next_document_index.h
        src/generic/stage1/json_minifier.h
        src/generic/stage1/json_scanner.h
        src/generic/stage1/json_string_scanner.h
        src/generic/stage1/json_structural_indexer.h
        src/generic/stage1/utf8_fastvalidate_algorithm.h
        src/generic/stage1/utf8_lookup2_algorithm.h
        src/generic/stage1/utf8_lookup3_algorithm.h
        src/generic/stage1/utf8_lookup4_algorithm.h
        src/generic/stage1/utf8_lookup_algorithm.h
        src/generic/stage1/utf8_range_algorithm.h
        src/generic/stage1/utf8_validator.h
        src/generic/stage1/utf8_zwegner_algorithm.h
        src/generic/stage2/json_iterator.h
        src/generic/stage2/logger.h
        src/generic/stage2/structural_iterator.h
        src/generic/stage2/tape_builder.h
        src/generic/stage2/tape_writer.h
        src/haswell/dom_parser_implementation.cpp
        src/haswell/implementation.cpp
        src/implementation.cpp
        src/internal/error_tables.cpp
        src/internal/jsoncharutils_tables.cpp
        src/internal/numberparsing_tables.cpp
        src/internal/simdprune_tables.cpp
        src/simdjson.cpp
        src/to_chars.cpp
        src/westmere/dom_parser_implementation.cpp
        src/westmere/implementation.cpp)
