#ifndef SIMDJSON_HASWELL_TARGET_H
#define SIMDJSON_HASWELL_TARGET_H

#include "simdjson/common_defs.h"

#if SIMDJSON_CAN_ALWAYS_RUN_HASWELL
#define SIMDJSON_TARGET_HASWELL
#define SIMDJSON_UNTARGET_HASWELL
#else
#define SIMDJSON_TARGET_HASWELL SIMDJSON_TARGET_REGION("avx2,bmi,pclmul,lzcnt,popcnt")
#define SIMDJSON_UNTARGET_HASWELL SIMDJSON_UNTARGET_REGION
#endif

#endif // SIMDJSON_HASWELL_TARGET_H