name: Doxygen GitHub Pages

on:
  release:
    # Trigger when a release object is created and when it's published.
    # Some GitHub flows create a release object then publish it later; include both.
    types: [created, published]
  # Also trigger on tag creation pushes so releasing via Git tags still runs the workflow
  push:
    tags:
      - "v*"  # common release tag pattern like v1.2.3
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Doxygen
        run: sudo apt-get install doxygen graphviz -y
      - run: mkdir docs
      - name: Install theme
        run: ./tools/prepare_doxygen.sh
      - name: Generate Doxygen Documentation
        run: doxygen
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/api/html
